### ISSUE TITLE
建议报错达到一定次数后自动停止翻译

### ISSUE THREAD

**Issue by TonokoTakatsuki** [XD2333/GalTransl#10]
如果我理解的不错，即便是失败的请求也会算一次请求吧，一直失败的话挺浪费额度的（
gpt3.5的极限亲测应该在一次24句左右，那个免费项目提供的一小时120次完全够用。
但是中间偶尔会因为莫名其妙的符号问题报错，如果不在边上看着及时调整的话就会很快刷完额度。。。

**Comment by TonokoTakatsuki** [comment]
关于符号报错的话，貌似日语的“ー”翻译成中文的破折号时也会报错，比如`おーーい、誰かーー！`这种，不知道是不是因为检测到两个破折号而当作重复了。

**Comment by XD2333** [comment]
24句可还行……目前正在把一些旧的判断代码逐步去掉，交给找问题系统记录就好了。

另外目前在逐步改成动态解析结果，即使输出不完整，可用的部分也会被解析，先给newbing和gpt4上

**Comment by TonokoTakatsuki** [comment]
> 24句可还行……目前正在把一些旧的判断代码逐步去掉，交给找问题系统记录就好了。
> 
> 另外目前在逐步改成动态解析结果，即使输出不完整，可用的部分也会被解析，先给newbing和gpt4上

好的好的，辛苦大佬

3.5现在24句没什么问题，官方更新gpt-3.5-turbo-16k后我把GPT3Translate.py里的模型改成了16k，但奇怪的是极限貌似没有增加，依然是24句左右，改回gpt-3.5-turbo-0613了，0613快是真的快（

newbing测试的极限在一次15句左右，稳定的话12句。

**Comment by XD2333** [comment]
fixed
