### ISSUE TITLE
翻译完打包报错

### ISSUE THREAD

**Issue by FFreQD** [xd2333/GalTransl#109]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 23: invalid start byte  

5.3版本没问题

**Comment by xd2333** [comment]
需要提供完整的报错截图，不然定位不到问题在哪。

**Comment by FFreQD** [comment]
> 需要提供完整的报错截图，不然定位不到问题在哪。

![RT](https://github.com/xd2333/GalTransl/assets/173282336/ad2abb02-cea3-4a71-a547-b518f2d694c5)

**Comment by FFreQD** [comment]
> 需要提供完整的报错截图，不然定位不到问题在哪。

更新到5.4.1能打包了
