### ISSUE TITLE
人工修改了缓存但似乎没办法锁定

### ISSUE THREAD

**Issue by fatecyx** [xd2333/GalTransl#113]
能否在缓存中增加一个字段存储人工修改后的pre_zh/proofread_zh，禁止AI因为retranslKey等原因覆盖人工修改的结果

**Comment by xd2333** [comment]
proofread_zh应该就是只要有内容就不应该被重翻的，目前可能有bug，我下一版检查一下

**Comment by xd2333** [comment]
fix in 5.5
