### ISSUE TITLE
name会导致强制换行

### ISSUE THREAD

**Issue by fatecyx** [xd2333/GalTransl#114]
原文为：
診療所「フォルコント」

缓存为：
 {
    "index": 3002,
    "name": "診療所",
    "pre_jp": "フォルコント",
    "post_jp": "フォルコント",
    "pre_zh": "佛尔柯特",
    "proofread_zh": "",
    "trans_by": "galtransl-v1",
    "proofread_by": "",
    "post_zh_preview": "佛尔柯特"
  },

结果为：
診療所
「佛尔柯特」

**Comment by fatecyx** [comment]
建议取消翻译时提取name
这一步应该提取文本时做的

**Comment by fatecyx** [comment]
再补充一下，我猜测同样是name引起的，大概是原文的「」因为name为空被删掉了
原文：
「当てル」
缓存：
 {
    "index": 511,
    "name": "",
    "pre_jp": "当てル",
    "post_jp": "当てル",
    "pre_zh": "打中了",
    "proofread_zh": "",
    "trans_by": "galtransl-v1",
    "proofread_by": "",
    "post_zh_preview": "打中了"
  },
结果：
打中了

**Comment by xd2333** [comment]
> 再补充一下，我猜测同样是name引起的，大概是原文的「」因为name为空被删掉了 原文： 「当てル」 缓存： { "index": 511, "name": "", "pre_jp": "当てル", "post_jp": "当てル", "pre_zh": "打中了", "proofread_zh": "", "trans_by": "galtransl-v1", "proofread_by": "", "post_zh_preview": "打中了" }, 结果： 打中了


pre_jp一定是GalTransl读取的原文，所以pre_jp没有对话框的话，是原文无对话框，或者读取的文件插件有问题。提供一下原始文本看看

**Comment by fatecyx** [comment]
之前搞错了，是file_translator++_xlsx这个插件的问题
[myProject.zip](https://github.com/user-attachments/files/16487328/myProject.zip)

**Comment by xd2333** [comment]
@PiDanShouRouZhouXD 

看下这里https://github.com/xd2333/GalTransl/blob/ef0bf15f0cf059b72ea437a5be677397b800746f/plugins/file_translator%2B%2B_xlsx/file_translator%2B%2B_xlsx.py#L23

是否应该是r"^(?P<name>.*?)(「?P<message>.*?」)$")，不然会导致name为空时message的「」符号不见了
