### ISSUE TITLE
Installation is stuck at building wheel

### ISSUE THREAD

**Issue by akinomushi** [XD2333/GalTransl#12]
**Expected behaviour**

I expected to module to install very fast.

**Actual behaviour**

Building wheel for tiktoken-0.4.0 takes forever to run.

**Steps to reproduce**

    OS - Windows 11 build 22621.1848
    architecture - x64
    python version - 3.12.0a5

**Comment by XD2333** [comment]
try use Python 3.11.4

**Comment by akinomushi** [comment]
> try use Python 3.11.4

I see, it works fine right now. Thank you for swift response.
