### ISSUE TITLE
关于译文中的引号导致译文识别失败

### ISSUE THREAD

**Issue by jyxjyx1234** [xd2333/GalTransl#127]
·最近在使用claude-sonnet模型时发现，模型容易在译文中把各种引号改成“，导致大面积的译文识别失败。
我在PROMPT 里加了一句
In the translation, do not use the " symbol. Use 「 and 」instead.
这样一定程度上缓解了这个问题

**Comment by TXT2GAM** [comment]
半角引号程序会自动修复，全角用译后字典
