### ISSUE TITLE
额，一直提示请求次数上限，5分钟后重试，但是手动在网页中输入是没有问题的

### ISSUE THREAD

**Issue by yuaniyuan** [XD2333/GalTransl#13]
如题.....

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/2.2.1

**Comment by XD2333** [comment]
https://github.com/acheong08/ChatGPT/issues/1431#issuecomment-1603993509

暂时又不可用了

**Comment by yuaniyuan** [comment]
> [acheong08/ChatGPT#1431 (comment)](https://github.com/acheong08/ChatGPT/issues/1431#issuecomment-1603993509)
> 
> 暂时又不可用了

裂了，我刚想说，现在用插件好像g了，mobile也限制....

**Comment by XD2333** [comment]
更新revChatGPT到6.4.2版，至少暂时是work的

python -m pip install --upgrade revChatGPT

**Comment by yuaniyuan** [comment]
> 更新revChatGPT到6.4.2版，至少暂时是work的
> 
> python -m pip install --upgrade revChatGPT

俺试试看，直接在项目根目录运行是吧

**Comment by XD2333** [comment]
> 更新revChatGPT到6.4.2版，至少暂时是work的
> 
> python -m pip install --upgrade revChatGPT

仍然不work，等他下一版吧

**Comment by XD2333** [comment]
6.4.4版revChatGPT可以了

python -m pip install --upgrade revChatGPT
