### ISSUE TITLE
5.6.2gt_input子目录时有两份缓存

### ISSUE THREAD

**Issue by fatecyx** [xd2333/GalTransl#132]
比如有个文件
gt_input/data/Armors.json.json
缓存会生成
data-}Armors.json.json
之后又会生成一份
Armors.json.json

data-}Armors.json.json里面，应该是翻译后的版本，没有之后的插件和problem之类的处理
Armors.json.json里面才是经过插件处理的，有problem相关信息的结果

但是程序读取缓存时，读的是data-}Armors.json.json，人工对Armors.json.json的任何修改都无效

**Comment by fatecyx** [comment]
第二次保存时的路径和第一次写的不一样，我抄过去就好了：
cache_file_path = joinpath(
                        projectConfig.getCachePath(), basename(file_name)
                    )
改成
cache_file_path = joinpath(
                        projectConfig.getCachePath(),
                        file_name.replace(projectConfig.getInputPath(), "").lstrip(os_sep).replace(os_sep, "-}")
                    )

**Comment by PiDanShouRouZhouXD** [comment]
> 比如有个文件 gt_input/data/Armors.json.json 缓存会生成 data-}Armors.json.json 之后又会生成一份 Armors.json.json
gt_input **不支持**多层文件夹结构，请打平层级后再翻译。
