### ISSUE TITLE
[QUERY] About META AI

### ISSUE THREAD

**Issue by HOKORISAMA** [xd2333/GalTransl#136]
Hello, First of all thanks for all the hard-work so far. I want to ask that is there any way to use META AI like BING AI , I mean through cookies or something because I noticed meta works great even without log in.

Thanks.

**Comment by xd2333** [comment]
There are currently no plans to continue maintaining models based on chat window cracking, so no new models (such as Meta AI) will be added, as these types of services have too many irreducible filters.

**Comment by HOKORISAMA** [comment]
Could you take a look at this repository it allows you to send messages to Meta AI with python and yields the result in json format.
[https://github.com/Strvm/meta-ai-api/tree/main](url)
