### ISSUE TITLE
请问如何使用mtool json？格式和需求格式不一致

### ISSUE THREAD

**Issue by Hummycookies** [xd2333/GalTransl#139]
我自己提取的脚本总是不全，想直接利用mtool json，但是好像格式是不一致的，请问是否有具体教程？

**Comment by xd2333** [comment]
参考 https://github.com/xd2333/GalTransl/blob/46a7fa698adaa8c9aa4b281f261a64f036e4d106/sampleProject/config.inc.yaml#L46

**Comment by Hummycookies** [comment]
好的，感谢您的帮助。
