### ISSUE TITLE
大佬我想问一下我是哪里搞错了吗，我用的是GPT-API-free的免费key，也挂了梯子，问题如图

### ISSUE THREAD

**Issue by 123dxx** [XD2333/GalTransl#14]
![QQ截图20230623195907](https://github.com/XD2333/GalTransl/assets/134991057/b01a0034-3991-4caa-8da3-c8f20e4aaada)

**Comment by XD2333** [comment]
删掉示例配置文件中多余的key      - token: sk-xxxxxxxx，只保留你自己的

**Comment by 123dxx** [comment]
大佬，很抱歉再次打扰你，我翻译时再次遇到了问题，就是翻译时不停的重复翻译同一段

**Comment by 123dxx** [comment]
![QQ截图20230624221738](https://github.com/XD2333/GalTransl/assets/134991057/6fa38b4a-3692-4a3c-a81c-19e2488e768d)

**Comment by XD2333** [comment]
尝试减少或增加每次翻译的句子数量
