### ISSUE TITLE
请求支持更多语言

### ISSUE THREAD

**Issue by Noriverwater** [XD2333/GalTransl#15]
建议增加原始文本为英语、韩语、俄语等语言的支持，如果目标语言也能切换就更好了。

**Comment by XD2333** [comment]
后续可以考虑支持，不过理论上只要你改改prompt就可以跑。

另外也可以提供一些其他语言的输入json给我测一测

**Comment by Noriverwater** [comment]
嗯，我就是这样做的，但还是希望能提供一个选项。这是一个韩语剧本示例：
[text.zip](https://github.com/XD2333/GalTransl/files/11860127/text.zip)

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/2.3.0
