### ISSUE TITLE
最新的包依赖有问题，更新依赖后就提示401 key错误

### ISSUE THREAD

**Issue by yuaniyuan** [XD2333/GalTransl#17]
![image](https://github.com/XD2333/GalTransl/assets/69374956/0da2d989-bb59-40a5-a0a4-ab8e0e692137)
装回上一个版本依赖后可以正常运行

**Comment by XD2333** [comment]
@yuaniyuan 什么模式？官方api还是模拟网页操作

**Comment by yuaniyuan** [comment]
> 

GPT4 官方api模式，不过是转发

**Comment by yuaniyuan** [comment]
> @yuaniyuan 什么模式？官方api还是模拟网页操作

GPT4 官方api模式，不过是转发

**Comment by XD2333** [comment]
python -m pip install --upgrade revChatGPT==6.5.0

升级一下依赖

**Comment by XD2333** [comment]
回退一下依赖 python -m pip install --upgrade revChatGPT==6.4.4

6.5.0有问题，等revChatGPT更新

**Comment by yuaniyuan** [comment]
> 回退一下依赖 python -m pip install --upgrade revChatGPT==6.4.4
> 
> 6.5.0有问题，等revChatGPT更新

okk

**Comment by yuaniyuan** [comment]
> 回退一下依赖 python -m pip install --upgrade revChatGPT==6.4.4
> 
> 6.5.0有问题，等revChatGPT更新

老哥问一下调用bing 一直提示https://www.bing.com/turing/conversation/create "HTTP/1.1 302 Found"咋搞，我给cookie放进json文件了，读取的时候路径也是对的...

**Comment by XD2333** [comment]
@yuaniyuan 挂代理

**Comment by yuaniyuan** [comment]
> 

对地区有要求吗，我试了香港 日本 新加坡 台湾，都是302

**Comment by yuaniyuan** [comment]
> @yuaniyuan 挂代理

对地区有要求吗，我试了香港 日本 新加坡 台湾，都是302
