### ISSUE TITLE
为什么翻着翻着变成了英文

### ISSUE THREAD

**Issue by ttkk907** [XD2333/GalTransl#19]
![QQ截图20230702130250](https://github.com/XD2333/GalTransl/assets/125134527/b11fcc4f-f2a2-4e94-ab55-a8a6cde4e3db)
[file.zip](https://github.com/XD2333/GalTransl/files/11928967/file.zip)

**Comment by ttkk907** [comment]
还有出现了这个就死循环了
![Uploading QQ截图20230702135031.png…]()

**Comment by ttkk907** [comment]
![QQ截图20230702135031](https://github.com/XD2333/GalTransl/assets/125134527/476905be-684b-4677-9e6b-05be162838aa)
还有出现了这个就死循环了

**Comment by XD2333** [comment]
附上出问题的文件

**Comment by ttkk907** [comment]
[file.zip](https://github.com/XD2333/GalTransl/files/11928939/file.zip)

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/2.3.3
