### ISSUE TITLE
bing无法使用

### ISSUE THREAD

**Issue by asd519020** [XD2333/GalTransl#21]
我在newbing提取了cookies，但是一直显示以下错误
![image](https://github.com/XD2333/GalTransl/assets/50279881/57e3e1f9-0f9a-446d-a6ad-99a55164c713)
![image](https://github.com/XD2333/GalTransl/assets/50279881/fdbf69da-6663-4e99-9fe4-4743612f1092)
![image](https://github.com/XD2333/GalTransl/assets/50279881/b9f69b22-5ee5-4d39-93d2-c4ae58a8c62b)
请问大佬该如何解决？

**Comment by XD2333** [comment]
要开启代理，或代理设置有问题，反正没走代理

**Comment by asd519020** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by asd519020** [comment]
> 要开启代理，或代理设置有问题，反正没走代理

  可是我用chatgpt3.5模仿网页的方法，在只开我自己的代理，没有设置config文件里面的代理设置的情况下，可以正常使用，只有bing不行。

**Comment by asd519020** [comment]
以自查解决问题，谢谢大佬！
