### ISSUE TITLE
大佬，很抱歉再次打扰你，我想问一下为什么环境安装不了

### ISSUE THREAD

**Issue by 123dxx** [XD2333/GalTransl#24]
![QQ截图20230723000148](https://github.com/XD2333/GalTransl/assets/134991057/c2785c29-defa-4b1e-8ef5-a502843d9ece)
![QQ截图20230722215325](https://github.com/XD2333/GalTransl/assets/134991057/dfb15648-871c-49e2-ba1d-faf6152987a0)

**Comment by 123dxx** [comment]
好几次了，一直卡在35.2mb这个里

**Comment by XD2333** [comment]
网络问题，尝试在参数后加-i https://pypi.tuna.tsinghua.edu.cn/simple
