### ISSUE TITLE
Newbing翻译请求次数超过30左右后报错，重试后正常运行

### ISSUE THREAD

**Issue by limoncello222** [XD2333/GalTransl#27]
如图，抱歉再次打扰，请大佬帮忙解答
<img width="744" alt="297ff887c39cbfcb07cb8b1bad89d5e" src="https://github.com/XD2333/GalTransl/assets/140846134/e63bac26-ba7e-4481-9152-4d88a04d2541">

**Comment by XD2333** [comment]
newbing上游库作者已停止维护。
https://github.com/acheong08/EdgeGPT#this-project-has-been-archived-due-to-personal-circumstances-i-lack-the-time-to-maintain-this-repository
