### ISSUE TITLE
不好意思，可以帮忙解决一下吗

### ISSUE THREAD

**Issue by dxx137** [XD2333/GalTransl#30]
![QQ截图20230812214519](https://github.com/XD2333/GalTransl/assets/140311615/9d0c3051-d7be-4393-a612-f6d06b07a405)

**Comment by dxx137** [comment]
翻译了一下好像是验证码

**Comment by dxx137** [comment]
翻译了一下好像要验证码，之前有一个还把一张图片塞在我的文件夹里要我验证

**Comment by XD2333** [comment]
模拟网页上游库作者已经放弃维护
https://github.com/acheong08/ChatGPT
