### ISSUE TITLE
使用UniversalInjectorFramework进行劫持时无法找到对应的dll

### ISSUE THREAD

**Issue by RoadToNowhereX** [XD2333/GalTransl#33]
BGI/Ethornell引擎，把winmm.dll和uif_config.json放到游戏根目录后启动游戏，启动失败并生成了uif_log.log文件，
提示如下：
DllMain: attach
InstallDelayedAttachHook: start
InstallDelayedAttachHook: no target module specified
InstallDelayedAttachHook: transaction
InstallDelayedAttachHook: end
游戏根目录下也找不到能够被劫持的dll

**Comment by RoadToNowhereX** [comment]
补充：VNTextProxy的每一个dll也都试过了，全部都能正常启动游戏，但是文本没有正常显示 。用微星小飞机找出来游戏是dx9渲染的，但是d3d9.dll也不行。

**Comment by XD2333** [comment]
可能得走GBK编码，或试一下https://github.com/satan53x/SExtractor/tree/main/tools/UniversalInjectorFramework
