### ISSUE TITLE
希望能加入0613模型和16k模型的选项

### ISSUE THREAD

**Issue by RoadToNowhereX** [XD2333/GalTransl#35]
现在2.5.0版本只有0301模型能用，不知道0613和16k有什么进步

PS.我闲得无聊又来提issue了

**Comment by XD2333** [comment]
默认模型就是0613了，现在是0301才需要指定。16k模型没什么提升

**Comment by hyominli** [comment]
> 默认模型就是0613了，现在是0301才需要指定。16k模型没什么提升

请问大佬在哪里换gpt4 turbo模型
