### ISSUE TITLE
两种会出错的情况。

### ISSUE THREAD

**Issue by wjzyxbaby** [XD2333/GalTransl#38]
"name": "優子",
    "message": "「あら……亮くん、寝ちゃったの？」"
  },
  {
    "message": "優子問いかけるように、声をかけるが、返事はない。"
  },

=================================================
像上面的这一句，message": "優子問いかけるように、声をかけるが、返事はない。"内容第一个词是名字優子【名字】，然后GPT翻译的时候，有时候回自动给你加上"name": "優子"在上面，变成下面这样
    "name": "優子",
    "message": "「あら……亮くん、寝ちゃったの？」"
  },
  {
     "name": "優子",
    "message": "優子問いかけるように、声をかけるが、返事はない。"
  },

然后返回的时候对不上就会出错，只返回【Failed translation】，其实内容都翻译了，就是多了gpt自作聪明的多加了"name": "優子"，返回的时候对不上就会出错。
=================================================
 "message": "優子曾经说，「声をかけるが、返事はない。」"
这样会翻译成
 "message": "優子曾经："翻译内容”"

这样也会出错。因为。会有最后那里两个双引号在最后，另一种情况是前面会有两个双引号在前面。这种时候就会报错，返回【Failed translation】
===============================================================
希望大佬看看有没办修复或者避免这两种出错的情况。

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/3.6.1
