### ISSUE TITLE
大佬咨询一下环境依赖问题

### ISSUE THREAD

**Issue by wuyeshayu** [XD2333/GalTransl#39]
大佬，想问一下我这个依赖为什么一直安装不了啊，我之前安装过python的3.10，然后按照教程把之前的python删除，重新安装的3.12，挂的美国vpn，然后就就弹出以下错误，一直安装不了依赖。

![捕获1](https://github.com/XD2333/GalTransl/assets/147145205/bc3b6e4f-eaf5-44a6-bc5b-bec2ab9fe3b0)
![捕获2](https://github.com/XD2333/GalTransl/assets/147145205/0f46784d-ada8-4fd4-966f-e70ef1dca797)

**Comment by yezhaoyi123** [comment]
是py版本问题

**Comment by XD2333** [comment]
需要python3.11
