### ISSUE TITLE
bing无法使用

### ISSUE THREAD

**Issue by mike1l3s** [XD2333/GalTransl#44]
![图片](https://github.com/XD2333/GalTransl/assets/148430091/ad5690e4-6888-404c-b11e-5fdc3c5ce96b)
求解答，已挂系统代理，config的vpn为false
顺便问下，哪种bing的cookie有效，必须是上面那个吗？
![图片](https://github.com/XD2333/GalTransl/assets/148430091/c1c19c04-4877-46a1-b770-dfab907e1526)
![图片](https://github.com/XD2333/GalTransl/assets/148430091/e3832e5f-dfbd-4674-b3ad-bc89385d628d)

**Comment by yuanhongyi** [comment]
解决了否？我也是这样子

**Comment by XD2333** [comment]
newbing估计已经不可用了，上游库作者几个月前停更了

**Comment by JE-Chen** [comment]
You can try this Bing GPT: https://github.com/Integration-Automation/ReEdgeGPT.
 I came here because GitHub suggested this repository to me.💯

**Comment by kzprkzzcu** [comment]
实测用楼上的ReEdgeGPT库可以，或者你找一个EdgeGPT的最近更新的fork项目替换掉原来的

**Comment by Ptilopsis01** [comment]
使用更新后的EdgeGPT会有报错：`Authentication failed. You have not been accepted into the beta.`
但我直接使用newbing是没有问题的，是cookie获取出现了问题吗？

**Comment by XD2333** [comment]
fix in https://github.com/XD2333/GalTransl/releases/tag/3.0.1
