### ISSUE TITLE
翻译注入文件后，游戏显示代码

### ISSUE THREAD

**Issue by jisadn** [XD2333/GalTransl#45]
![图片](https://github.com/XD2333/GalTransl/assets/148298476/fa5dc87e-4ff7-41e9-88f2-efb7561c68bc)
系统为catsystem2，会显示代码（GBK也显示代码）
使用UniversalInjector后显示为
![图片](https://github.com/XD2333/GalTransl/assets/148298476/74487cf4-93e1-4449-aa17-e954c8002ffb)
请问如何解决呢？

**Comment by ryank231231** [comment]
请在 https://github.com/AtomCrafty/UniversalInjectorFramework/issues open issue, 该部分代码不由 GalTransl 维护。
