### ISSUE TITLE
请问可以实现集成Claude来翻译吗，通过slack(没有api)

### ISSUE THREAD

**Issue by yuaniyuan** [XD2333/GalTransl#5]

**Comment by XD2333** [comment]
Claude有测试，在我这套体系下翻译效果不好

**Comment by yuaniyuan** [comment]
> 克劳德有测试，在我这套身体系下翻译效果不好

好吧，我找了个别人写好的脚本，通过slack的api来调用claude，速度比gpt3.5要快点。我试着对比了1000行文本，感觉Claude略胜于3.5，只是slack里的Claude回复的格式有时候会乱掉，各种情况都有，后面整理起来费神，没有直接调api来的规整

**Comment by yuaniyuan** [comment]
感谢大佬提供的工具，个人第一部机翻终于做好了(´▽`)ﾉ

**Comment by yuaniyuan** [comment]
> Claude有测试，在我这套体系下翻译效果不好

老哥，我试了试gpt4的网页版，为啥开了校润，会无限重复校润，文本一直发送的是第一段，一直到次数上限....

**Comment by cx9208** [comment]
> > Claude有测试，在我这套体系下翻译效果不好
> 
> 老哥，我试了试gpt4的网页版，为啥开了校润，会无限重复校润，文本一直发送的是第一段，一直到次数上限....

我晚点测试下

**Comment by yuaniyuan** [comment]
> > > Claude有测试，在我这套体系下翻译效果不好
> > 
> > 
> > 老哥，我试了试gpt4的网页版，为啥开了校润，会无限重复校润，文本一直发送的是第一段，一直到次数上限....
> 
> 我晚点测试下

麻烦老哥了，对了还有俩问题，我试了试bing，会提示EdgeGPT错误返回403，我去EdgeGPT的issues看了，有人有相同的问题，版本都是0.10.11，不知道是我的问题还是。另一个就是关于gpt4模拟网页的请求次数限制，我看不是有那个解除限制的油猴脚本嘛，我试了试确实没有限制，通过ios客户端的GPT4。不知道该项目能否调用他那个来优化体验
https://greasyfork.org/zh-CN/scripts/467317-chatgpt%E5%BC%80%E5%90%AF%E4%B8%8D%E9%99%90%E6%AC%A1%E6%95%B0%E7%9A%84gpt4-mobile

**Comment by XD2333** [comment]
> > > > Claude有测试，在我这套体系下翻译效果不好
> > > 
> > > 
> > > 老哥，我试了试gpt4的网页版，为啥开了校润，会无限重复校润，文本一直发送的是第一段，一直到次数上限....
> > 
> > 
> > 我晚点测试下
> 
> 麻烦老哥了，对了还有俩问题，我试了试bing，会提示EdgeGPT错误返回403，我去EdgeGPT的issues看了，有人有相同的问题，版本都是0.10.11，不知道是我的问题还是。另一个就是关于gpt4模拟网页的请求次数限制，我看不是有那个解除限制的油猴脚本嘛，我试了试确实没有限制，通过ios客户端的GPT4。不知道该项目能否调用他那个来优化体验 https://greasyfork.org/zh-CN/scripts/467317-chatgpt%E5%BC%80%E5%90%AF%E4%B8%8D%E9%99%90%E6%AC%A1%E6%95%B0%E7%9A%84gpt4-mobile

403是你的代理问题。gpt4只要你修改GPT4Translate.py https://github.com/XD2333/GalTransl/blob/24323c8979f17b836a7d33f89b8735f13882b589/GalTransl/Backend/GPT4Translate.py#L129 ，将gpt-4改成gpt-4-mobile即可

**Comment by yuaniyuan** [comment]
> > > > > Claude有测试，在我这套体系下翻译效果不好
> > > > 
> > > > 
> > > > 老哥，我试了试gpt4的网页版，为啥开了校润，会无限重复校润，文本一直发送的是第一段，一直到次数上限....
> > > 
> > > 
> > > 我晚点测试下
> > 
> > 
> > 麻烦老哥了，对了还有俩问题，我试了试bing，会提示EdgeGPT错误返回403，我去EdgeGPT的issues看了，有人有相同的问题，版本都是0.10.11，不知道是我的问题还是。另一个就是关于gpt4模拟网页的请求次数限制，我看不是有那个解除限制的油猴脚本嘛，我试了试确实没有限制，通过ios客户端的GPT4。不知道该项目能否调用他那个来优化体验 https://greasyfork.org/zh-CN/scripts/467317-chatgpt%E5%BC%80%E5%90%AF%E4%B8%8D%E9%99%90%E6%AC%A1%E6%95%B0%E7%9A%84gpt4-mobile
> 
> 403是你的代理问题。gpt4只要你修改GPT4Translate.py
> 
> https://github.com/XD2333/GalTransl/blob/24323c8979f17b836a7d33f89b8735f13882b589/GalTransl/Backend/GPT4Translate.py#L129
> 
> ，将gpt-4改成gpt-4-mobile即可

感谢老哥回复，我试试看。我节点是jp的，难道是因为节点质量不够吗...
