### ISSUE TITLE
是否可以加一个超时重试功能

### ISSUE THREAD

**Issue by bluedomain** [XD2333/GalTransl#52]
最近我用GalTransl加GPT3.5 Turbo的时候，经常性的突然无法收到GPT API回复，持续时间可能是无限，有一次我特地等了一个小时也没有任何变化。必须手动关闭程序然后再启动来继续下去。
这有可能是OpenAI服务器的问题。
是否可以加一个超时重试机制？比如超过30秒没有收到任何回复就重新发一次请求。

**Comment by XD2333** [comment]
确实有这个问题

**Comment by XD2333** [comment]
试下这个版本，还有问题的话再把issue打开~
https://github.com/XD2333/GalTransl/releases/tag/3.1.1
