### ISSUE TITLE
是否考虑加入sakura模型支持

### ISSUE THREAD

**Issue by gulaodeng** [XD2333/GalTransl#55]
相关链接
https://github.com/SakuraLLM/Sakura-13B-Galgame
https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/translator/sakura.py

可能稍微差点，但是可以离线跑

**Comment by SXK485** [comment]
我的老笔记本连翻译姬都跑不动😢

**Comment by Isotr0py** [comment]
Sakura模型后端可以用colab/kaggle的免费GPU配合内网穿透完成API部署，autogptq量化模型基本都能跑。

colab/kaggle部署后端API的Example：[SakuraLLM-Notebooks](https://github.com/Isotr0py/SakuraLLM-Notebooks)

Sakura模型的API跟openai挺像的，可惜就是没有详细的API文档

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/3.1.0
