### ISSUE TITLE
译前字典变化导致post_jp改变触发重翻

### ISSUE THREAD

**Issue by chuliu-hash** [XD2333/GalTransl#65]
能不能加个只根据字典替换post_jp之类的的开关而不进行翻译，不然都不太敢动通用的译前字典，之前翻的有些想通过译后字典修改也要注意通用译前字典有没有变化

**Comment by XD2333** [comment]
测试一下
https://github.com/XD2333/GalTransl/commit/176289168b22b8d5f9a6612ad9006194ddc7b543

**Comment by chuliu-hash** [comment]
> 测试一下 [1762891](https://github.com/XD2333/GalTransl/commit/176289168b22b8d5f9a6612ad9006194ddc7b543)

解压时忘了会覆盖字典了，虽然点了取消解压但字典好像还是被覆盖了，我得先检查下字典

**Comment by XD2333** [comment]
建议是把自己的字典挪出去，然后修改  defaultDictFolder: Dict ，可以填入绝对路径

**Comment by chuliu-hash** [comment]
> 建议是把自己的字典挪出去，然后修改 defaultDictFolder: Dict ，可以填入绝对路径

这个rebulid模式如果我的字典不一样了，那么受影响的几个句子好像就直接没了 比如我译后有个繁体字替换为简体字，如果我把这个替换删了，所有受影响的句子都直接没了

**Comment by chuliu-hash** [comment]
> > 建议是把自己的字典挪出去，然后修改 defaultDictFolder: Dict ，可以填入绝对路径
> 
> 这个rebulid模式如果我的字典不一样了，那么受影响的几个句子好像就直接没了 比如我译后有个繁体字替换为简体字，如果我把这个替换删了，所有受影响的句子都直接没了

好像我说的不对，但确实是有句子直接没了，因为我现在的字典是默认的，跟原先自己的区别比较大

**Comment by chuliu-hash** [comment]
好像是译前字典变化的问题，有的句子直接没了，有的pre_zh是空值，

**Comment by XD2333** [comment]
再试下

https://github.com/XD2333/GalTransl/commit/7a1090a9d1085df44564cab56cd933058f87b4b3

**Comment by chuliu-hash** [comment]
> 再试下
> 
> [7a1090a](https://github.com/XD2333/GalTransl/commit/7a1090a9d1085df44564cab56cd933058f87b4b3)

好像可以了，句子是没少了

**Comment by chuliu-hash** [comment]
原文有「」包着的对话好像在post_jp去掉后没有再加回去，结果都是没有「」的

> > 再试下
> > [7a1090a](https://github.com/XD2333/GalTransl/commit/7a1090a9d1085df44564cab56cd933058f87b4b3)
> 
> 好像可以了，句子是没少了

原文有「」包着的对话好像在post_jp去掉后没有再加回去，结果都是没有「」的

**Comment by chuliu-hash** [comment]
现在可以了，话说为啥post_jp不用译前字典重构下，译后字典有些也是用post_jp当条件的

**Comment by chuliu-hash** [comment]
> 再试下
> 
> [edeaec3](https://github.com/XD2333/GalTransl/commit/edeaec32a211b3a56654762652134eddf9cb9bc8)

现在可以了，话说为啥post_jp不用译前字典重构下，译后字典有些也是用post_jp当条件的

**Comment by XD2333** [comment]
> > 再试下
> > [edeaec3](https://github.com/XD2333/GalTransl/commit/edeaec32a211b3a56654762652134eddf9cb9bc8)
> 
> 现在可以了，话说为啥post_jp不用译前字典重构下，译后字典有些也是用post_jp当条件的

有道理。之前是考虑如果post_jp也改变，然后写入cache的话，就不再会被其他翻译器重翻了

**Comment by XD2333** [comment]
LGTM
https://github.com/XD2333/GalTransl/commit/4aac9b97327a76c3a745ff27cd2c947f3712bd21

**Comment by chuliu-hash** [comment]
> LGTM [4aac9b9](https://github.com/XD2333/GalTransl/commit/4aac9b97327a76c3a745ff27cd2c947f3712bd21)

也就是说现在这个是直接替换不会修改cache嘛，我看结果和post_zh_preview是不一样的

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/3.4.0
