### ISSUE TITLE
关于识别余额耗尽的key的问题

### ISSUE THREAD

**Issue by SXK485** [XD2333/GalTransl#66]
`if "quota" in str_ex:......`的判断是否应该放在`if "try again later" in str_ex or "too many requests" in str_ex:......`之前，因为对于openai官方，余额耗尽返回的str_ex也会包含"too many requests"，导致会先走`if "try again later" in str_ex or "too many requests" in str_ex:......`的逻辑，而不是走`if "quota" in str_ex:......`的逻辑

**Comment by XD2333** [comment]
有道理，感谢反馈。

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/3.5.0
