### ISSUE TITLE
使用Sakura模型进行翻译时没有回复

### ISSUE THREAD

**Issue by RoadToNowhereX** [XD2333/GalTransl#67]
在kaggle上跑的，日志如下：
2024-01-18 03:30:20 61defda0feb4 api[244] INFO Incoming request api: http://e16b-34-173-102-4.ngrok-free.app/v1/chat/completions
2024-01-18 03:30:20 61defda0feb4 api[244] INFO client: Address(host='127.0.0.1', port=42354)
2024-01-18 03:30:20 61defda0feb4 api.openai.v1.chat[244] INFO translate: [{'role': 'system', 'content': '你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。'}, {'role': 'user', 'content': '将下面的日文文本翻译成中文：\\\n―親子―\n\\\n\\\n\\\n\\\n\\\n\\\n\\'}, {'role': 'user', 'content': '将下面的日文文本翻译成中文：運がない\nそう他人に言われることも、そう自身で嘆くことにも飽き飽きしていた。\n生まれてからこの方、幸運に恵まれた記憶など一度もない。\n強いて言えば、そんな状況の中で生きてこられたことが幸運とも言えなくもないが……。\nだが、それすらも……今この瞬間に。\nなっ、なぜ……？！\n振り向けば、黒いスーツ姿の大男が注射器らしい器具を持っていた。\n首筋に刺さる小さな痛み。続いて感じたのは、血管に入り込む冷たい異物感。\nだったら、止めてくれればいい'}]
2024-01-18 03:30:20 61defda0feb4 api.openai.v1.chat[244] INFO current generation config: 
{'do_sample': True,
 'max_new_tokens': 3619,
 'messages': [{'content': '你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。',
               'role': 'system'},
              {'content': '将下面的日文文本翻译成中文：\\\n―親子―\n\\\n\\\n\\\n\\\n\\\n\\\n\\',
               'role': 'user'},
              {'content': '将下面的日文文本翻译成中文：運がない\n'
                          'そう他人に言われることも、そう自身で嘆くことにも飽き飽きしていた。\n'
                          '生まれてからこの方、幸運に恵まれた記憶など一度もない。\n'
                          '強いて言えば、そんな状況の中で生きてこられたことが幸運とも言えなくもないが……。\n'
                          'だが、それすらも……今この瞬間に。\n'
                          'なっ、なぜ……？！\n'
                          '振り向けば、黒いスーツ姿の大男が注射器らしい器具を持っていた。\n'
                          '首筋に刺さる小さな痛み。続いて感じたのは、血管に入り込む冷たい異物感。\n'
                          'だったら、止めてくれればいい',
               'role': 'user'}],
 'model': 'gpt-3.5-turbo',
 'n': 1,
 'seed': -1,
 'temperature': 0.1,
 'top_k': 40,
 'top_p': 0.3,
 'transformers_version': '4.33.2'}

发现发送给服务器请求的模型是GPT3.5，而在轻小说机翻机器人网页测试能正常翻译时的日志是这样的：
2024-01-18 03:29:11 61defda0feb4 api[244] INFO Incoming request api: http://e16b-34-173-102-4.ngrok-free.app/v1/chat/completions
2024-01-18 03:29:11 61defda0feb4 api[244] INFO client: Address(host='127.0.0.1', port=59034)
2024-01-18 03:29:11 61defda0feb4 api.openai.v1.chat[244] INFO translate: <|im_start|>system
你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>
<|im_start|>user
将下面的日文文本翻译成中文：　剣を振り下ろした男が呆然と、受け止められる刀身とそれを防いだ俺の左腕を眺める。俺は水しぶきを防ぐかのような軽い動作で最後の一発を受け止めた。ずっと外套の下に隠していた、その――金属製の堅牢な義手で。
「悪いな、俺の左腕は特別製なんだ」
「な……！？」
　魔粒子を原動力に、実際に神経を繋いで可動することができる無機物の手足――魔動義肢。俺はそれを、過去に失った左腕の代わりに装着していた。
　そして突然の切り札登場に唖然とする盗賊Ａへ目掛けて。
「ふんっ！」
「……っ」
　義手で強烈なボディブローをお見舞いすると、そいつはろくに悲鳴すら残すことができずに――はるか彼方、山頂方向へとぶっ飛んでいった。
「な、なんだあのパワー……！？」
「魔動義肢って、普通に動かすのも難しいって話じゃ……」
「ごめんな、悪気があって隠してたわけじゃないんだ」
　俺はたった今ひとりの山賊をあの世に送った義手の可動を確認するようにぎにぎしながら、残った皆様へ向き直る。
「ほら、一応これ精密機械だろ？　中に砂とかが入らないよう普段はマントで覆ってるんだ」
「は、はぁ……」
「あと今やったみたいに不意打ちもできるしな」<|im_end|>
<|im_start|>assistant

Llama.generate: prefix-match hit

llama_print_timings:        load time =     653.87 ms
llama_print_timings:      sample time =      34.75 ms /   278 runs   (    0.12 ms per token,  8000.46 tokens per second)
llama_print_timings: prompt eval time =    1006.07 ms /   382 tokens (    2.63 ms per token,   379.70 tokens per second)
llama_print_timings:        eval time =   14084.04 ms /   277 runs   (   50.84 ms per token,    19.67 tokens per second)
llama_print_timings:       total time =   20136.38 ms
{'choices': [{'finish_reason': 'stop',
              'index': 0,
              'logprobs': None,
              'text': '挥下剑的男子呆呆地望着被挡下的刀身和我防御的左臂。我用像是在防备水花般的轻巧动作挡下了最后一击。用一直藏在外套下的——金属制的坚固义手。\n'
                      '「抱歉啊，我的左臂是特制的。」\n'
                      '「什……！？」\n'
                      '以魔粒子为原动力，实际上可以连接神经活动的无机物手脚——魔动义肢。我把它装在了过去失去的左臂上。\n'
                      '然后朝着因为突然的王牌登场而哑然的盗贼A。\n'
                      '「哼！」\n'
                      '「……」\n'
                      '用义手给予他强烈的腹部攻击后，那家伙连惨叫都没能发出——就飞向了遥远的彼方，山顶的方向。\n'
                      '「那、那是什么力量……！？」\n'
                      '「魔动义肢，不是说连正常活动都很困难吗……」\n'
                      '「抱歉啊，我并不是有恶意才藏起来的。」\n'
                      '我为了确认刚才把一名山贼送往那个世界的义手的可动性而活动着关节，重新面向剩下的大家。\n'
                      '「你看，这姑且算是精密机械吧？为了不让沙子之类的东西进去，平时都用斗篷盖着。」\n'
                      '「哦、哦……」\n'
                      '「还有，也能像刚才那样偷袭。」'}],
 'created': 1705548551,
 'id': 'cmpl-ea43036a-9353-41ec-828b-7cc6f2d33e41',
 'model': './models/sakura-13b-lnovel-v0.9-Q8_0.gguf',
 'object': 'text_completion',
 'usage': {'completion_tokens': 277, 'prompt_tokens': 447, 'total_tokens': 724}}
注意到这里请求的模型是sakura

**Comment by RoadToNowhereX** [comment]
本地终端日志：
[2024-01-18 16:39:28,748][INFO]->输入：
\
\
\（な、何をして……瑞樹ッ、あなた何をしてるのッッ！！）
\
―親子―
\
\
\　一瞬にして眠気が吹き飛ぶと、薄目のまま間近にある息子の……オチンポを見てしまう。
\

[2024-01-18 16:39:30,280][INFO]HTTP Request: POST https://16f9-35-227-92-53.ngrok-free.app/v1/chat/completions "HTTP/1.1 503 Service Unavailable"
Traceback (most recent call last):
  File "D:\Tools\GalTrans\GalTransl-main-v3.5.0\GalTransl\Backend\SakuraTranslate.py", line 109, in translate
    async for data in ask_stream:
  File "D:\Tools\GalTrans\GalTransl-main-v3.5.0\GalTransl\Backend\revChatGPT\V3.py", line 287, in ask_stream_async
    raise t.APIConnectionError(
GalTransl.Backend.revChatGPT.typings.APIConnectionError: 503 Service Unavailable <!DOCTYPE html>
<html class="h-full" lang="en-US" dir="ltr">
  <head>
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Regular-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-RegularItalic-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Medium-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Semibold-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-MediumItalic-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-Text.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-TextItalic.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-SemiBold.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-SemiBoldItalic.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <meta charset="utf-8">
    <meta name="author" content="ngrok">
    <meta name="description" content="ngrok is the fastest way to put anything on the internet with a single command.">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link id="style" rel="stylesheet" href="https://cdn.ngrok.com/static/css/error.css">
    <noscript>ngrok gateway error
The server returned an invalid or incomplete HTTP response. (ERR_NGROK_3004)</noscript>
    <script id="script" src="https://cdn.ngrok.com/static/js/error.js" type="text/javascript"></script>
  </head>
  <body class="h-full" id="ngrok">
    <div id="root" data-payload="eyJjZG5CYXNlIjoiaHR0cHM6Ly9jZG4ubmdyb2suY29tLyIsImNvZGUiOiIzMDA0IiwibWVzc2FnZSI6Im5ncm9rIGdhdGV3YXkgZXJyb3JcblRoZSBzZXJ2ZXIgcmV0dXJuZWQgYW4gaW52YWxpZCBvciBpbmNvbXBsZXRlIEhUVFAgcmVzcG9uc2UuIiwidGl0bGUiOiJTZXJ2aWNlIFVuYXZhaWxhYmxlIn0="></div>
  </body>
</html>

Please check if there is a problem with your network connection
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
[2024-01-18 16:39:30,285][INFO]-> 报错:503 Service Unavailable <!DOCTYPE html>
<html class="h-full" lang="en-US" dir="ltr">
  <head>
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Regular-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-RegularItalic-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Medium-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-Semibold-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/euclid-square/EuclidSquare-MediumItalic-WebS.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-Text.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-TextItalic.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-SemiBold.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <link rel="preload" href="https://cdn.ngrok.com/static/fonts/ibm-plex-mono/IBMPlexMono-SemiBoldItalic.woff" as="font" type="font/woff" crossorigin="anonymous" />
    <meta charset="utf-8">
    <meta name="author" content="ngrok">
    <meta name="description" content="ngrok is the fastest way to put anything on the internet with a single command.">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link id="style" rel="stylesheet" href="https://cdn.ngrok.com/static/css/error.css">
    <noscript>ngrok gateway error
The server returned an invalid or incomplete HTTP response. (ERR_NGROK_3004)</noscript>
    <script id="script" src="https://cdn.ngrok.com/static/js/error.js" type="text/javascript"></script>
  </head>
  <body class="h-full" id="ngrok">
    <div id="root" data-payload="eyJjZG5CYXNlIjoiaHR0cHM6Ly9jZG4ubmdyb2suY29tLyIsImNvZGUiOiIzMDA0IiwibWVzc2FnZSI6Im5ncm9rIGdhdGV3YXkgZXJyb3JcblRoZSBzZXJ2ZXIgcmV0dXJuZWQgYW4gaW52YWxpZCBvciBpbmNvbXBsZXRlIEhUVFAgcmVzcG9uc2UuIiwidGl0bGUiOiJTZXJ2aWNlIFVuYXZhaWxhYmxlIn0="></div>
  </body>
</html>
, 立刻重试

**Comment by RoadToNowhereX** [comment]
找到503的原因了，Kaggle似乎不支持多个访问请求，不能用多线程，否则Kaggle会自动停止模型，只能单个文件慢慢翻译。
不知道本地部署能不能多线程？

**Comment by XD2333** [comment]
不能，一个部署只能同时处理一个请求。

所以理论上得多次部署，然后用个什么东西把所有的部署汇总起来，自动负载均衡，才能做到多线程（
