### ISSUE TITLE
希望添加基于ai的人名提取功能

### ISSUE THREAD

**Issue by TXT2GAM** [xd2333/GalTransl#69]
据我观察目前并没有较好的轻小说的人名提取方式。隔壁轻小说机翻机器人网站给出的一个方案是**统计片假名词组的出现频次**。不过只适用于大部分角色名均为片假名的情况。
那么能否考虑修改gpt的prompt，让gpt自行收集gpt字典里没有记录的人名？这个设想的前提是之后会进行二次翻译，目前gpt3.5的价格十分低廉，还是非常值得开发这个功能的。

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl_Name_Detector
