### ISSUE TITLE
GalTransl 提取注入工具GBK编码注入有问题

### ISSUE THREAD

**Issue by kangmeiyuanchao** [XD2333/GalTransl#8]
引擎是ADVHD（WillPlus），游戏是[220325] [Guilty dash] 女体でもてなす接待旅館，SJIS是可以正常注入，但是选择GBK编码注入后文件会停止第一个文件，然后工具就变未响应了
![图片](https://github.com/XD2333/GalTransl/assets/89840896/ca621817-da2f-49fe-970f-15331fedbc6c)

**Comment by XD2333** [comment]
是有问题，在尝试修
