### ISSUE TITLE
请问用sjis隧道和替换模式都无法还原空白文字怎么办

### ISSUE THREAD

**Issue by asdhaiusd** [xd2333/GalTransl#87]
游戏是辻堂さんの純愛ロード，脚本导出和输入都没有问题，用隧道模式的dll试了一遍没有能够成功还原的，仍然显示为“口”。
用替换模式无法启动游戏，报错log如下：
DllMain: attach
InstallDelayedAttachHook: start
InstallDelayedAttachHook: no target module specified
InstallDelayedAttachHook: transaction
InstallDelayedAttachHook: end
DllMain: detach
求教大佬有无解决方法，感谢感谢

**Comment by xd2333** [comment]
还有一种邪道是直接使用经过jis替换定制的字体文件，只要让游戏切换到使用那个字体就能正常显示，可以参考
https://github.com/satan53x/SExtractor/blob/main/document/1_JIS%E6%9B%BF%E6%8D%A2%E5%AE%9E%E4%BE%8B_Alicesoft.MD#24-jis替换

**Comment by asdhaiusd** [comment]
好的，非常感谢！
