### ISSUE TITLE
对括号识别有问题

### ISSUE THREAD

**Issue by TonokoTakatsuki** [XD2333/GalTransl#9]
翻译诸如
`キース・ジャレットの９９年のアルバム、『The Melody at Night , With You』から、『My Wild Irish Rose』。`
`自分も目の端を拭って、笑って答える。「ありがとう」と。`
这样的句子就会报错，GPT3.5会提示“多余括号”不断重试，newbing直接跳出。

将`GalTransl\Backend\GPT3Translate.py`中的
```
                # 多余符号
                elif ("(" in result[key_name] or "（" in result[key_name]) and (
                    "(" not in content[i].post_jp and "（" not in content[i].post_jp
                ):
                    LOGGER.info(
                        f"->第{content[i].index}句多余括号：" + result[key_name] + "\n"
                    )
                    error_flag = True
                    break

```
把True改成False就行了，估计是判定规则有点问题？

**Comment by XD2333** [comment]
这块明天的版本会统一改一下，这个判断现在是不太需要的，直接去掉算了

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/release_230618
