### ISSUE TITLE
Question about the new CHAT GPT 4 O model

### ISSUE THREAD

**Issue by HOKORISAMA** [xd2333/GalTransl#91]
Hi there, thank you for everything so far.
So I was just asking that as Open AI has released a new model CHAT GPT 4 O that costs about half of the cost of chat gpt 4 turbo and I want to know that if GalTransl supports translating through this model or not. I have tried changing the name of model in config.yaml but when i run GalTransl it gives error like `Invalid Open AI Token`.

Thanks.

**Comment by xd2333** [comment]
hi, gpt4o should work with rewriteModelName: "gpt-4o-2024-05-13". maybe you can try check your key with ChatGPT-Next-Web or somelse

**Comment by HOKORISAMA** [comment]
I am getting this error--
![image](https://github.com/xd2333/GalTransl/assets/160050298/e0c68a61-a54a-424f-b18a-551afa4fc388)

**Comment by xd2333** [comment]
> I am getting this error-- ![image](https://private-user-images.githubusercontent.com/160050298/332001840-e0c68a61-a54a-424f-b18a-551afa4fc388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTAzMTYsIm5iZiI6MTcxNjIxMDAxNiwicGF0aCI6Ii8xNjAwNTAyOTgvMzMyMDAxODQwLWUwYzY4YTYxLWE1NGEtNDI0Zi1iMThhLTU1MWFmYTRmYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMzAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWQ2ZmNiOGFhMzY3OWQ1ZDc1MTQ2ZTIwNjkyYTU2ODEyMjljMmRhMjliYWE4NTk0MzhhNjI2YjQ4YjI2ODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FtpejEtFxUNx5kxTTMv1ZWC4-1wnv2vK1j4ZS_0Z3O4)

try run `pip install tiktoken --upgrade` in cmd

**Comment by HOKORISAMA** [comment]
> gpt-4o-2024-05-13

Thanks, It's working with the latest version of Galtransl.
