### ISSUE TITLE
遇到2个问题

### ISSUE THREAD

**Issue by jeshs** [xd2333/GalTransl#92]
1、翻译完成后，如果不想手动处理翻译问题，怎么做才能让 galtransl 自动重试。例如“残留日文、比日文长”等问题，能否在下图运行界面加个重试已检测问题的选项，自动翻译有问题的条目

![image](https://github.com/xd2333/GalTransl/assets/43285002/dc153cfa-85c8-4880-8f32-657f769fd3cf)

2、是否支持 Gemini ，试了下提示“[WARNING]AIzaSy***************** is not available for gemini-1.5-pro-latest, will be removed”

**Comment by xd2333** [comment]
```
  retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
```

gemini暂未支持，但你可以使用例如one-api等项目将gemini中转为openai接口然后自行尝试一下

**Comment by jeshs** [comment]
> ```
>   retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
> ```
> 
> gemini暂未支持，但你可以使用例如one-api等项目将gemini中转为openai接口然后自行尝试一下

好的，retranslKey设置后，翻译中断或全部完成，启动时都支持吗？另外retranslKey多个值有什么格式要求吗，例如这样可以吗："残留日文 词频过高"

**Comment by chace9208** [comment]
> > ```
> >   retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gemini暂未支持，但你可以使用例如one-api等项目将gemini中转为openai接口然后自行尝试一下
> 
> 好的，retranslKey设置后，翻译中断或全部完成，启动时都支持吗？另外retranslKey多个值有什么格式要求吗，例如这样可以吗："残留日文 词频过高"

目前只是简单的查找触发，所以只能每次设置一个关键词。这个设置项的表现跟设置项的备注是一致的，即“包含此关键字”

**Comment by xd2333** [comment]
> > ```
> >   retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gemini暂未支持，但你可以使用例如one-api等项目将gemini中转为openai接口然后自行尝试一下
> 
> 好的，retranslKey设置后，翻译中断或全部完成，启动时都支持吗？另外retranslKey多个值有什么格式要求吗，例如这样可以吗："残留日文 词频过高"

`翻译中断或全部完成，启动时都支持吗`——是的
`另外retranslKey多个值有什么格式要求吗`——只支持每次单个关键词

**Comment by jeshs** [comment]
> > > ```
> > >   retranslKey: "" # 重启时主动重翻在problem或pre_jp中包含此关键字的句子，例如"残留日文"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > gemini暂未支持，但你可以使用例如one-api等项目将gemini中转为openai接口然后自行尝试一下
> > 
> > 
> > 好的，retranslKey设置后，翻译中断或全部完成，启动时都支持吗？另外retranslKey多个值有什么格式要求吗，例如这样可以吗："残留日文 词频过高"
> 
> `翻译中断或全部完成，启动时都支持吗`——是的 `另外retranslKey多个值有什么格式要求吗`——只支持每次单个关键词

明白了，感谢大佬！
